### ISSUE TITLE
Spotify-api.js v9 todo list.

### ISSUE THREAD

**Issue by Scientific-Guy** [spotify-api/spotify-api.js#55]
# Spotify-api.js v9 todo list

- [ ] Add `Get Recommendations` API.
- [ ] Make better error handler.
- [ ] Make cache manager work with less efforts.
- [ ] Add auto updating token.

> Further suggestions or changes can be added below.
